apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42playground
spec:
  project: app-dev
  source:
    repoURL: https://github.com/AdrienCN/iot-adconsta.git
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
      automated:
          prune: true
          selfHeal: true

