Vagrant.configure("2") do | config |
	config.vm.box = "centos/stream8"

	#Define server machine
	config.vm.define "adconstaS" do | web |
		web.vm.network "public_network", ip: "192.168.42.110"
		web.vm.hostname = "adconstaShostname"
		web.vm.provider "virtualbox" do |vb|
			vb.name = "adconstaBoxServer"
			vb.memory = 512
			vb.cpus = 1
			vb.gui = false
		end
		web.vm.provision "shell" do |s|
			s.inline = "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=server sh -"
		end
	end

	#Define worker machine
	config.vm.define "adconstaSW" do | web |
		web.vm.network "public_network", ip: "192.168.42.111"
		web.vm.hostname = "adconstaSWhostname"
		web.vm.provider "virtualbox" do |vb|
			vb.name = "adconstaBoxWorker"
			vb.memory = 512
			vb.cpus = 1
			vb.gui = false
		end
		web.vm.provision "shell" do |s|
			#INSTALL K3S
			s.inline = "curl -sfL https://get.k3s.io | INSTALL_K3S_NAME=k3s-agent sh -"
		end
	end
end
