Vagrant.configure("2") do | config |
	config.vm.box = "centos/stream8"
CPU = 1
MEMORY = 1024
MASTER_IP = "192.168.42.110"
WORKER_IP = "192.168.42.111"
MASTER_NAME = "adconstaS"
WORKER_NAME = "adconstaSW"
PROVIDER = "virtualbox"


	#Define server machine
	config.vm.define MASTER_NAME do | web |
		web.vm.network "private_network", ip: MASTER_IP
		web.vm.hostname = MASTER_NAME
		web.vm.provider PROVIDER do |vb|
			vb.name = MASTER_NAME
			vb.cpus = CPU
			vb.memory = MEMORY 
		end
		web.vm.provision "shell" do |s|
			#INSTALL K3S and IFCONFIG
			s.inline = "curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 INSTALL_K3S_EXEC=server sh -"
		end
	end

	#Define worker machine
	config.vm.define WORKER_NAME do | web |
		web.vm.network "private_network", ip: WORKER_IP
		web.vm.hostname = WORKER_NAME
		web.vm.provider PROVIDER do |vb|
			vb.name = WORKER_NAME
			vb.cpus = CPU
			vb.memory = MEMORY
		end
		web.vm.provision "shell" do |s|
			#INSTALL K3S and IFCONFIG
			s.inline = "curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 INSTALL_K3S_NAME=k3s-agent sh -"
		end
	end
end
