#!/usr/bin/env ruby

CPU = 1
MEMORY = 1024
MASTER_IP = "192.168.42.110"
WORKER_IP = "192.168.42.111"
MASTER_NAME = "adconstaS"
WORKER_NAME = "adconstaSW"
PROVIDER = "virtualbox"


$master_script = <<-SCRIPT
#Enable ssh connection
sudo mkdir -p /root/.ssh
sudo cp /tmp/id_rsa.pub /root/.ssh/authorized_keys

curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 \
	K3s_NODE_NAME=#{MASTER_NAME} \
	INSTALL_K3S_NAME=k3s \
	INSTALL_K3S_EXEC=--flannel-iface=eth1 \
	sh -
SCRIPT

$worker_script = <<-SCRIPT
mkdir -p /root/.ssh
cp /tmp/id_rsa	/root/.ssh
scp -o StrictHostKeyChecking=no	root@#{MASTER_IP}:/var/lib/rancher/k3s/server/token /tmp/token
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 \
	K3s_NODE_NAME=#{WORKER_NAME} \
	K3S_URL=https://#{MASTER_IP}:6443 \
	K3S_TOKEN_FILE="/tmp/token" \
	INSTALL_K3S_EXEC=--flannel-iface=eth1 \
	sh - 
SCRIPT


Vagrant.configure("2") do | config |
	config.vm.box = "centos/stream8"
	config.vm.synced_folder ".", "/vagrant"
	config.vm.provider "virtualbox" do |vb|
		vb.cpus = CPU
		vb.memory = MEMORY
	end

	# Define server machine
	config.vm.define MASTER_NAME do | master |
			#BIND 192.168.42.110 on eth1
		master.vm.network "private_network", ip: MASTER_IP
		master.vm.hostname = MASTER_NAME
		master.vm.provider PROVIDER do |vb|
			vb.name = MASTER_NAME
		end
		master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/"
		master.vm.provision "shell", inline: $master_script
	end
	 # Define worker machine
	 config.vm.define WORKER_NAME do | worker |
		worker.vm.network "private_network", ip: WORKER_IP
		worker.vm.hostname = WORKER_NAME
		worker.vm.provider PROVIDER do |vb|
			vb.name = WORKER_NAME
		end
		worker.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/"
		worker.vm.provision "shell", inline: $worker_script
	end
end
